name: Test Suite

defaults:
  run:
    working-directory: backend

on:
  push:
    branches: [main]

jobs:
  tests:
    name: Smart Contracts Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js v22.1.0
        uses: actions/setup-node@v1
        with:
          node-version: v22.1.0

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: 'backend/node_modules'
          key: node_modules-${{ hashFiles('backend/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
  
      - name: Run Tests
        run: npx hardhat coverage

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          target: 'backend/contracts'
          node-version: 16
          fail-on: none
          slither-args: --solc-remaps @openzeppelin=backend/node_modules/@openzeppelin --filter-paths "node_modules"
        #  run: slither . --filter-paths "node_modules"